name = "echodit-api-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV namespaces for secure operations
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "fbd3ff6ccb6c47e59f7279e629642a1b"  # Replace with actual KV namespace ID

[[kv_namespaces]]
binding = "DEVICE_KEYS"
id = "device-keys-namespace-id"  # Replace with actual KV namespace ID

[[kv_namespaces]]
binding = "CREDITS"
id = "credits-namespace-id"  # Replace with actual KV namespace ID

[[kv_namespaces]]
binding = "USED_TRANSACTIONS"
id = "used-transactions-namespace-id"  # Replace with actual KV namespace ID

[[kv_namespaces]]
binding = "GENERATION_LOGS"
id = "generation-logs-namespace-id"  # Replace with actual KV namespace ID

# Environment variables (set via Cloudflare dashboard or CLI)
[vars]
# These are non-sensitive variables that can be in git
WORKER_ENV = "production"
BUNDLE_ID = "stevenstrange.EchoEdit"
APPLE_SANDBOX = true  # Set to false for production

# Secret variables (set via: wrangler secret put SECRET_NAME)
# Don't put actual values here - use wrangler secret commands
# FLUX_API_KEY = "your-flux-api-key"
# APPLE_SHARED_SECRET = "your-app-store-shared-secret"
# 
# Commands to set secrets:
# wrangler secret put FLUX_API_KEY
# wrangler secret put APPLE_SHARED_SECRET
